params:
  seed              : 0 # main program's random seed

  dataset:
    tmin              : 0.
    tmax              : 5.
    n_samples         : 1024
    seq_len           : 64 # sequence length of each samples
    batch_size        : 13 # batch's size
    noise_scale       : 1e-2 

  model:
    u_dim             : 2
    mlp_layers        : [3, 16, 19, 2]

  solver:
    h_max             : 0.101

  training:
    n_iter          : 101
    learning_rate   : 1e-2

